# YAML格式默认配置项
app:
  name: springboot-case-yaml
  port: 8000

# 导入其他配置文件
spring:
  config:
    import: conf/db.yml, conf/redis.yml

# 激活环境
  profiles:
    active: dev

app1:
  name: springboot-case
  port: 3306
  security:
    username: root
    password: root

security:
  username: root
  password: root