# YAML格式默认配置项
app:
  name: springboot-case-yaml
  port: 8000

# 导入其他配置文件
spring:
  config:
    import: conf/db.yml, conf/redis.yml

# 激活环境
  profiles:
    active: dev

app1:
  name: springboot-case
  port: 3306
  security:
    username: root
    password: root

security:
  username: root
  password: root

# 配置集合属性
# Array
names:
  - John
  - Jonathan
  - Alice

# List
servers:
  - title: 东北一区
    ip: 204.1.165.24
  - title: 华北一区
    ip: 15.145.0.34

# Map
users:
  user1:
    name: John
    age: 21
  user2:
    name: Jonathan
    age: 23