# 服务器相关配置
server:
  port: 8080
  servlet:
    context-path: /springboot
    encoding:
      charset: UTF-8
      force: true
  # Tomcat相关配置
  tomcat:
    accesslog:
      enabled: true
      directory: D:\Workspace\SpringBoot\log
      prefix: springboot_log
      file-date-format: .yyyy-MM-dd
      suffix: .log
    max-http-form-post-size: 50MB

# Dispatcher相关配置
spring:
  mvc:
    servlet:
      path: /
      load-on-startup: 1
    format:
      date-time: yyyy-MM-dd HH:mm:ss