# 配置DataSource
spring:
  datasource:
    # 默认就是 Hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password: root
    hikari:
      auto-commit: true
      # 估算公式 [(CPU Core Number * 2) + Disk Number]
      maximum-pool-size: 10
      connection-test-query: select 1
      connection-timeout: 2000
      # MySQL推荐设置项
      data-source-properties:
        cachePrepStmts: true
        dataSource.cachePrepStmts: true
        dataSource.prepStmtCacheSize: 250
        dataSource.prepStmtCacheSqlLimit: 2048
        dataSource.userServerPrepStmts: true
# 配置MyBatis
mybatis:
  configuration:
    # 关闭驼峰转换 测试ResultMap
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 为XML配置文件开启别名
  type-aliases-package: pers.johns.springboot.mybatis.model.pojo